version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            flake8 --exclude=venv* --statistics
            pytest -v --cov=calculator
      #Step 4: install Artifactory
      - run:
          name: Install jFrog CLI
          command: curl -fL https://getcli.jfrog.io | sh
      #Step 5: Run application
      - run:
          name : Run calculator
          command: |
            python Calculator.py
      #Step 6: store artifact
      - store_artifacts:
          path: calculator.log